### PR TITLE
#4 - bug fix proposal

### PR DESCRIPTION
**Pull request by sbomber**
Proposal for addressing what I reported on https://github.com/pluyckx/iar-vsc/issues/4

### CODE REVIEW

**Comment by pluyckx** [comment]
Thank you for the fix proposal. I will try to validate your changes asap. If I do not find any issue I will merge your pull request. Otherwise I will let you know and we can see how we can improve the fix.

Just one remark in case you make more changes for which you create a pull request:
I saw that all changes are done in one commit. Some changes are not necessarily related to the fix, but are just some code cleanups/corrections (like using == instead of ===). It would be nice if you could split them in different commits next time.
For this pull request it is ok and you can leave it as it is now. I think it is more important that the issue gets fixed.

**Comment by sbomber** [comment]
On the topic of pull requests…okay.  Since I am new to GitHub, it this your preference or typical GitHub process?

Where I work we have ~30 developers running wild doing what they want with SVN commits.  I am happy to follow a procedure.



On Dec 8, 2018, at 7:47 AM, Philip Luyckx <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for the fix proposal. I will try to validate your changes asap. If I do not find any issue I will merge your pull request. Otherwise I will let you know and we can see how we can improve the fix.

Just one remark in case you make more changes for which you create a pull request:
I saw that all changes are done in one commit. Some changes are not necessarily related to the fix, but are just some code cleanups/corrections (like using == instead of ===). It would be nice if you could split them in different commits next time.
For this pull request it is ok and you can leave it as it is now. I think it is more important that the issue gets fixed.

**Comment by pluyckx** [comment]
It is both, it is my preference, but also an advice from Github. You can read a bit about the flow they propose: https://guides.github.com/introduction/flow/. Especially the second part *Add Commits* is about why it is better to split commits.

The most important reasons are:
* There is more history, so it is easier for other developers to see why some changes are made
* It is easier to roll back a change. For example, If I do not agree with the code cleanup you have done or it cause a new bug, it is easier for you (or me) to revert that commit. Now we would have to revert everything by hand.
* Small commits are easier to maintain

Currently I am cleaning up the extension and reworking the architecture a bit. I also plan to change the project directory layout so I can add more documentation for developers who want to help me with the extension. I hope I can finish this at the end of this year.

**Comment by pluyckx** [comment]
@sbomber I have a questions about your IAR setup. Which directories are available on your system where you can find the `common` and `install-info` directories (by default something like `C:\Pogram Files (x86)\IAR Systems\Embedded Workbench x.y`) where x.y is the version of your embedded workbench.
I think there is a difference how we setup our IAR environments and that is why the issue never occurred on my system.

**Comment by sbomber** [comment]
For my installation of 8.0, 430 and arm

**Comment by sbomber** [comment]
Oops hit wrong button on my phone

**Comment by pluyckx** [comment]
I have split your commit in more commits and pulled you merge. It is now available in the master.
I will create a new beta release and publish it on Github. I will probably create an official release this weekend in case no issues are found.

**Pull request closed without merging**
